### ISSUE TITLE
Failed to run the bgp_peer example.

### ISSUE THREAD

**Issue by chris3will** [nsg-ethz/synet-plus#32]
I'm using my virtual machine, ubutnu20 LTS and player15.

I just download the z3, z3solver, and using my python 2.7 for the 2018's version.

then I download the requirements for synet-plus and the token.

when I run the bgp_peers, the things mostly seemed run well, but after printing the "Constraints adding time : xxxxx
Start Z3 check xxxx
Z3 check time: xxx
Setting the Var: xxx
Reading model time:xxxx
" 

then it  comes the error:
Traceback (most recent call last):
  File "bgp_peers.py", line 212, in <module>
    bgp_example(args.outdir)
  File "bgp_peers.py", line 203, in bgp_example
    netcomplete.synthesize()
  File "/home/chris/Downloads/synet-plus-master/synet/netcomplete.py", line 362, in synthesize
    self.synthesize_bgp()
  File "/home/chris/Downloads/synet-plus-master/synet/netcomplete.py", line 184, in synthesize_bgp
    self.bgp_synthesizer.update_network_graph()
  File "/home/chris/Downloads/synet-plus-master/synet/synthesis/new_propagation.py", line 435, in update_network_graph
    self.ibgp_propagation.node[node]['box'].update_network_graph()
  File "/home/chris/Downloads/synet-plus-master/synet/synthesis/new_bgp.py", line 607, in update_network_graph
    rmap = smt_rmap.get_config()
  File "/home/chris/Downloads/synet-plus-master/synet/utils/fnfree_policy.py", line 1670, in get_config
    lines.append(line.get_config())
  File "/home/chris/Downloads/synet-plus-master/synet/utils/fnfree_policy.py", line 1572, in get_config
    actions = self.smt_actions.get_config()
  File "/home/chris/Downloads/synet-plus-master/synet/utils/fnfree_policy.py", line 1448, in get_config
    config = _gather_communities(communities, index)
  File "/home/chris/Downloads/synet-plus-master/synet/utils/fnfree_policy.py", line 1430, in _gather_communities
    assert isinstance(prev_action, ActionSetCommunity), "Found: {}".format(self.actions)
AssertionError: Found: [SetPermitted(EMPTY?Value), SetActions([SetNextHop(EMPTY?V(p(p((((((py(p(p(p((((("

so i don't know what to do , and if there is something caused by the new version nowadays 2020? 
thanks for your idea! plz

**Comment by Tokisakii** [comment]
Did you solve the problem? I have the same confusion
